#!/bin/bash

set -e

red="\e[0;31m"
green="\e[0;32m"
off="\e[0m"

function banner() {

	clear
	echo "  _____ _     _____                       ";              
	echo " |_   _| |__ | ___/       ____  _ __      ";              
	echo "   | | | '_ \| |_        |  __|| '_ \     ";              
	echo "   | | | | | | |__       | |   | | | \    ";          
	echo "   |_| |_| |_|____\      |_|   |_| |_|    ";          
	echo "                                          ";              
	echo "  ___            _        _ _             ";              
	echo " |_ _| _ __  ___| |_ __ _| | | ___ ___    ";              
	echo "  | | | '_ \/ __| __/ _\` | | |/ _ \ __\  ";              
	echo "  | | | | | \__ \ || (_| | | |  __/ |     ";              
	echo " |___||_| |_|___/\__\__,_|_|_|\___|_|     ";              
	echo "                                          ";              

}

rn_installer() {

	local bin_dir share_dir script_dir

	script_dir="$(dirname "${0}")"              # directory of this script
	script_dir="$(readlink -f "${script_dir}")" # Make sure absolute path

	share_dir=/usr/share/
	prog_dir=/usr/share/rnelome
	bin_dir=/usr/local/bin/

	echo -e "$red [$green+$red]$off Installing Perl ...";
	sudo apt-get install -y perl >/dev/null
	echo -e "$red [$green+$red]$off Installing Pcre2grep ...";
	sudo apt-get install -y pcre2-utils >/dev/null
	echo -e "$red [$green+$red]$off Checking directories..."
	if [ -d "${share_dir}" ]; then
		echo -e "$red [$green+$red]$off A Directory rnelome Was Found! Do You Want To Replace It? [Y/n]:" ;
		read -N 1 -sr replace
		if [ "$replace" = "y" ]; then
			#sudo rm -rfv "${prog_dir}"
			sudo unlink "${bin_dir}/rn"
			sudo unlink "/etc/bash_completion.d/rn.bash"

		else
			echo -e "$red [$green✘$red]$off If You Want To Install You Must Remove Previous Installations";
			echo -e "$red [$green✘$red]$off Installation Failed";
			exit
		fi
	fi 

	echo -e "$red [$green+$red]$off Installing ...";
	#sudo -H cp -r -t "${share_dir}" "${script_dir}"/*
	sudo -H git clone "${script_dir}" "${share_dir}"
	sudo -H chmod +x ${prog_dir}/{Error_Handle,Help_Usage,Rename,Signal_Handler,_Check_Input,_Get_Input,rn,search_plugin,show_status}
	sudo -H ln -s "${prog_dir}/rn" "${bin_dir}/rn"
	sudo -H ln -s "${prog_dir}/rn_completion" "/etc/bash_completion.d/rn.bash"

	if [ -d "${prog_dir}" ] ;
	then
		echo -e "$red [$green+$red]$off Tool Successfully Installed And Will Start In 5s!";
		echo -e "$red [$green+$red]$off You can execute tool by typing rn"
		sleep 5;
	else
		echo -e "$red [$green✘$red]$off Tool Cannot Be Installed On Your System! Use It As Portable !";
		exit
	fi 
}

banner
rn_installer
