#!/bin/bash

set -e

red="\e[0;31m"
green="\e[0;32m"
off="\e[0m"

function banner() {

	clear
	echo "  _____ _     _____                       ";              
	echo " |_   _| |__ | ___/       ____  _ __      ";              
	echo "   | | | '_ \| |_        |  __|| '_ \     ";              
	echo "   | | | | | | |__       | |   | | | \    ";          
	echo "   |_| |_| |_|____\      |_|   |_| |_|    ";          
	echo "                                          ";              
	echo "  ___            _        _ _             ";              
	echo " |_ _| _ __  ___| |_ __ _| | | ___ ___    ";              
	echo "  | | | '_ \/ __| __/ _\` | | |/ _ \ __\  ";              
	echo "  | | | | | \__ \ || (_| | | |  __/ |     ";              
	echo " |___||_| |_|___/\__\__,_|_|_|\___|_|     ";              
	echo "                                          ";              

}

rn_installer() {

	local prog_dir script_dir req_package

	script_dir="$(dirname "${0}")"              # directory of this script
	script_dir="$(readlink -f "${script_dir}")" # Make sure absolute path

	prog_dir=/usr/local/bin/rnelome

	req_package=(perl pcre2-utils)

	echo -e "$red [$green+$red]$off Checking requirements ..."
	sleep 1
	for package in "${req_package[@]}"; do
		
		if dpkg -s "${package}" &> /dev/null; then
			echo -e "$red [$green+$red]$off ${package} is installed!";
		else
			echo -e "$red [$green+$red]$off ${package} is NOT installed!";
			echo -e "$red [$green+$red]$off Installing ${package} ...";
			#sudo apt-get install -y "${package}" >/dev/null
		fi
	done

	echo -e "$red [$green+$red]$off Checking directories..."
	sleep 1
	if [ -d "${prog_dir}" ]; then
		echo -e "$red [$green+$red]$off A Directory rnelome Was Found! Do You Want To Replace It? [Y/n]:" ;
		read -N 1 -sr replace
		if [ "$replace" = "y" ]; then
			echo -e "$red [$green✘$red]$off Removing Previous Installations ...";
			sudo rm -rf "${prog_dir}"
			if [ -L "/etc/bash_completion.d/rn.bash" ]; then
				sudo unlink "/etc/bash_completion.d/rn.bash"
			fi
			if [ -L "/usr/local/bin/rn" ]; then
				sudo unlink "/usr/local/bin/rn"
			fi
		else
			echo -e "$red [$green✘$red]$off If You Want To Install You Must Remove Previous Installations";
			echo -e "$red [$green✘$red]$off Installation Aborted";
			exit 1
		fi
	fi 

	echo -e "$red [$green+$red]$off Installing ...";
	sleep 1
	#sudo -H cp -r -t "${share_dir}" "${script_dir}"/*
	sudo -H git clone "${script_dir}" "${prog_dir}"
	sudo -H chmod +x ${prog_dir}/{Error_Handle,Help_Usage,Rename,Signal_Handler,_Check_Input,_Get_Input,rn,search_plugin,show_status}
	sudo -H ln -s "${prog_dir}/rn" "/usr/local/bin/rn"
	sudo -H ln -s "${prog_dir}/rn_completion" "/etc/bash_completion.d/rn.bash"

	if [ -d "${prog_dir}" ] ;
	then
		echo -e "$red [$green+$red]$off Tool Successfully Installed And Will Start In 5s!";
		echo -e "$red [$green+$red]$off You can execute tool by typing rn"
		sleep 5;
	else
		echo -e "$red [$green✘$red]$off Tool Cannot Be Installed On Your System! Use It As Portable !";
		exit
	fi 
}

banner
rn_installer
